// src/components/pages/projects/$projectId/shared/connect-snippets/web/vue/src/App.vue
<script setup lang="ts">
import { ref, onMounted, computed } from 'vue'
import { client } from './lib/appwrite'
import { Account } from 'appwrite'
import SignIn from './pages/SignIn.vue'
import SignUp from './pages/SignUp.vue'

const user = ref<{ name: string } | null>(null)
const loading = ref(true)

onMounted(async () => {
  try {
    const account = new Account(client)
    const u = await account.get()
    user.value = { name: u.name }
  } catch {
    user.value = null
  } finally {
    loading.value = false
  }
})

async function handleSignOut() {
  const account = new Account(client)
  await account.deleteSession({ sessionId: 'current' })
  user.value = null
}

const path = computed(() => window.location.pathname)
</script>

<template>
  <SignIn v-if="path === '/sign-in'" />
  <SignUp v-else-if="path === '/sign-up'" />
  <div v-else>
    <p v-if="loading">Loading...</p>
    <template v-else-if="!user">
      <p>Sign in to get started.</p>
      <p>
        <a href="/sign-in">Sign in</a>
        &middot;
        <a href="/sign-up">Sign up</a>
      </p>
    </template>
    <template v-else>
      <p>Hello, {{ user.name }}</p>
      <button type="button" @click="handleSignOut">Sign out</button>
    </template>
  </div>
</template>

// apps/console/src/components/pages/projects/$projectId/shared/connect-snippets/web/svelte/src/App.svelte
<script lang="ts">
  import { onMount } from 'svelte'
  import { Account } from 'appwrite'
  import { client } from './lib/appwrite'
  import SignIn from './pages/SignIn.svelte'
  import SignUp from './pages/SignUp.svelte'

  const path = window.location.pathname

  let user: { name: string } | null = $state(null)
  let loading = $state(true)

  onMount(async () => {
    try {
      const account = new Account(client)
      const u = await account.get()
      user = { name: u.name }
    } catch {
      user = null
    } finally {
      loading = false
    }
  })

  async function handleSignOut() {
    const account = new Account(client)
    await account.deleteSession({ sessionId: 'current' })
    user = null
  }
</script>

{#if path === '/sign-in'}
  <SignIn />
{:else if path === '/sign-up'}
  <SignUp />
{:else if loading}
  <p>Loading...</p>
{:else if user}
  <p>Hello, {user.name}</p>
  <button type="button" onclick={handleSignOut}>Sign out</button>
{:else}
  <p>Sign in to get started.</p>
  <p>
    <a href="/sign-in">Sign in</a>
    {' · '}
    <a href="/sign-up">Sign up</a>
  </p>
{/if}
