// apps/console/src/components/pages/projects/$projectId/shared/connect-snippets/web/sveltekit/src/routes/+page.svelte
<script lang="ts">
  import { invalidateAll } from '$app/navigation'
  import { Account } from 'appwrite'
  import { client } from '$lib/appwrite'

  let { data } = $props()

  let loading = $state(false)

  async function handleSignOut() {
    loading = true
    try {
      const account = new Account(client)
      await account.deleteSession({ sessionId: 'current' })
      await invalidateAll()
    } catch (err) {
      console.error(err)
    } finally {
      loading = false
    }
  }
</script>

<div>
  {#if loading}
    <p>Loading...</p>
  {:else if data.user}
    <p>Hello, {data.user.name}</p>
    <button type="button" onclick={handleSignOut}>Sign out</button>
  {:else}
    <p>Sign in to get started.</p>
    <p>
      <a href="/sign-in">Sign in</a>
      {' · '}
      <a href="/sign-up">Sign up</a>
    </p>
  {/if}
</div>

// apps/console/src/components/pages/projects/$projectId/shared/connect-snippets/web/tanstack/src/routes/index.tsx
import { createFileRoute, Link, useRouter } from '@tanstack/react-router'
import { Account } from 'appwrite'
import { client } from '../lib/appwrite'

export const Route = createFileRoute('/')({
  ssr: false,
  loader: async () => {
    const account = new Account(client)
    const user = await account.get().catch(() => null)
    return { user }
  },
  component: Home,
})

function Home() {
  const router = useRouter()
  const { user } = Route.useLoaderData()

  if (!user) {
    return (
      <div>
        <p>Sign in to get started.</p>
        <p>
          <Link to="/sign-in">Sign in</Link>
          {' · '}
          <Link to="/sign-up">Sign up</Link>
        </p>
      </div>
    )
  }

  async function handleSignOut() {
    const account = new Account(client)
    await account.deleteSession({ sessionId: 'current' })
    await router.invalidate()
  }

  return (
    <div>
      <p>Hello, {user.name}</p>
      <button type="button" onClick={handleSignOut}>
        Sign out
      </button>
    </div>
  )
}
