// apps/console/src/components/pages/projects/$projectId/shared/connect-snippets/web/solidstart/src/routes/sign-in.tsx
import { A, revalidate, useNavigate } from '@solidjs/router'
import { createSignal, Show } from 'solid-js'
import { Account } from 'appwrite'
import { client } from '../lib/appwrite'

export default function SignInPage() {
  const navigate = useNavigate()
  const [email, setEmail] = createSignal('')
  const [password, setPassword] = createSignal('')
  const [error, setError] = createSignal('')

  async function handleSubmit(e: SubmitEvent) {
    e.preventDefault()
    setError('')
    try {
      const account = new Account(client)
      await account.createEmailPasswordSession({
        email: email(),
        password: password(),
      })
      await revalidate('user')
      navigate('/')
    } catch (err) {
      setError(err instanceof Error ? err.message : 'Sign in failed')
    }
  }

  return (
    <form onSubmit={handleSubmit}>
      <h1>Sign in</h1>
      <Show when={error()}>
        <p>{error()}</p>
      </Show>
      <input
        type="email"
        placeholder="Email"
        value={email()}
        onInput={(e) => setEmail(e.currentTarget.value)}
        required
      />
      <input
        type="password"
        placeholder="Password"
        value={password()}
        onInput={(e) => setPassword(e.currentTarget.value)}
        required
      />
      <button type="submit">Sign in</button>
      <p>
        No account? <A href="/sign-up">Sign up</A>
      </p>
    </form>
  )
}

// apps/console/src/components/pages/projects/$projectId/shared/connect-snippets/web/tanstack/src/routes/sign-in.tsx
import { useState, type SubmitEvent } from 'react'
import { createFileRoute, Link, useRouter } from '@tanstack/react-router'
import { Account } from 'appwrite'
import { client } from '../lib/appwrite'

export const Route = createFileRoute('/sign-in')({
  ssr: false,
  component: SignInPage,
})

function SignInPage() {
  const router = useRouter()
  const [email, setEmail] = useState('')
  const [password, setPassword] = useState('')
  const [error, setError] = useState('')

  async function handleSubmit(e: SubmitEvent<HTMLFormElement>) {
    e.preventDefault()
    setError('')
    try {
      const account = new Account(client)
      await account.createEmailPasswordSession({ email, password })
      await router.invalidate()
      await router.navigate({ to: '/' })
    } catch (err) {
      setError(err instanceof Error ? err.message : 'Sign in failed')
    }
  }

  return (
    <form onSubmit={handleSubmit}>
      <h1>Sign in</h1>
      {error ? <p>{error}</p> : null}
      <input
        type="email"
        placeholder="Email"
        value={email}
        onChange={(e) => setEmail(e.target.value)}
        required
      />
      <input
        type="password"
        placeholder="Password"
        value={password}
        onChange={(e) => setPassword(e.target.value)}
        required
      />
      <button type="submit">Sign in</button>
      <p>
        No account? <Link to="/sign-up">Sign up</Link>
      </p>
    </form>
  )
}
