// src/components/pages/projects/$projectId/shared/connect-snippets/web/svelte/src/App.svelte
<script lang="ts">
  import { onMount } from 'svelte'
  import { client } from './lib/appwrite'
  import { Account } from 'appwrite'

  let user: { name: string } | null = null

  onMount(async () => {
    try {
      const account = new Account(client)
      const u = await account.get()
      user = { name: u.name }
    } catch {
      // Not signed in
    }
  })
</script>

<div>
  {#if user}
    <p>Hello, {user.name}</p>
  {:else}
    <p>Sign in to get started.</p>
  {/if}
</div>

// src/components/pages/projects/$projectId/shared/connect-snippets/react-native/App.tsx
import { useEffect, useState } from 'react'
import { client } from './lib/appwrite'
import { Account } from 'react-native-appwrite'

export default function App() {
  const [user, setUser] = useState<{ name: string } | null>(null)

  useEffect(() => {
    const account = new Account(client)
    account.get().then((u) => setUser({ name: u.name })).catch(() => {})
  }, [])

  return (
    <div>
      {user ? <p>Hello, {user.name}</p> : <p>Sign in to get started.</p>}
    </div>
  )
}
