// src/components/pages/projects/$projectId/shared/connect-snippets/web/vue/src/pages/SignUp.vue
<script setup lang="ts">
import { ref } from 'vue'
import { Account, ID } from 'appwrite'
import { client } from '../lib/appwrite'

const name = ref('')
const email = ref('')
const password = ref('')
const error = ref('')

async function handleSubmit(event: Event) {
  event.preventDefault()
  error.value = ''
  try {
    const account = new Account(client)
    await account.create({
      userId: ID.unique(),
      email: email.value,
      password: password.value,
      name: name.value,
    })
    await account.createEmailPasswordSession({ email: email.value, password: password.value })
    window.location.href = '/'
  } catch (err) {
    error.value = err instanceof Error ? err.message : 'Sign up failed'
  }
}
</script>

<template>
  <form @submit="handleSubmit">
    <h1>Sign up</h1>
    <p v-if="error">{{ error }}</p>
    <input
      v-model="name"
      type="text"
      placeholder="Name"
    />
    <input
      v-model="email"
      type="email"
      placeholder="Email"
      required
    />
    <input
      v-model="password"
      type="password"
      placeholder="Password"
      required
    />
    <button type="submit">Sign up</button>
    <p>
      Already have an account? <a href="/sign-in">Sign in</a>
    </p>
  </form>
</template>

// src/components/pages/projects/$projectId/shared/connect-snippets/web/svelte/src/pages/SignUp.svelte
<script lang="ts">
  import { Account, ID } from 'appwrite'
  import { client } from '../lib/appwrite'

  let name = $state('')
  let email = $state('')
  let password = $state('')
  let error = $state('')

  async function handleSubmit(e: SubmitEvent) {
    e.preventDefault()
    error = ''
    try {
      const account = new Account(client)
      await account.create({
        userId: ID.unique(),
        email,
        password,
        name,
      })
      await account.createEmailPasswordSession({ email, password })
      window.location.href = '/'
    } catch (err) {
      error = err instanceof Error ? err.message : 'Sign up failed'
    }
  }
</script>

<form onsubmit={handleSubmit}>
  <h1>Sign up</h1>
  {#if error}
    <p>{error}</p>
  {/if}
  <input
    type="text"
    placeholder="Name"
    bind:value={name}
  />
  <input
    type="email"
    placeholder="Email"
    bind:value={email}
    required
  />
  <input
    type="password"
    placeholder="Password"
    bind:value={password}
    required
  />
  <button type="submit">Sign up</button>
  <p>
    Already have an account? <a href="/sign-in">Sign in</a>
  </p>
</form>
