// src/components/pages/projects/$projectId/shared/connect-snippets/web/react/cra/src/pages/SignUp.js
import { useState } from 'react'
import { Account, ID } from 'appwrite'
import { client } from '../lib/appwrite'

export function SignUp() {
  const [name, setName] = useState('')
  const [email, setEmail] = useState('')
  const [password, setPassword] = useState('')
  const [error, setError] = useState('')

  async function handleSubmit(e) {
    e.preventDefault()
    setError('')
    try {
      const account = new Account(client)
      await account.create({
        userId: ID.unique(),
        email,
        password,
        name: name.trim() || undefined,
      })
      await account.createEmailPasswordSession({ email, password })
      window.location.href = '/'
    } catch (err) {
      setError(err?.message || 'Sign up failed')
    }
  }

  return (
    <form onSubmit={handleSubmit}>
      <h1>Sign up</h1>
      {error ? <p>{error}</p> : null}
      <input
        type="text"
        placeholder="Name"
        value={name}
        onChange={(e) => setName(e.target.value)}
      />
      <input
        type="email"
        placeholder="Email"
        value={email}
        onChange={(e) => setEmail(e.target.value)}
        required
      />
      <input
        type="password"
        placeholder="Password"
        value={password}
        onChange={(e) => setPassword(e.target.value)}
        required
      />
      <button type="submit">Sign up</button>
      <p>
        Already have an account? <a href="/sign-in">Sign in</a>
      </p>
    </form>
  )
}

// src/components/pages/projects/$projectId/shared/connect-snippets/web/solid/src/pages/SignUp.tsx
import { createSignal, Show } from 'solid-js'
import { Account, ID } from 'appwrite'
import { client } from '../lib/appwrite'

export function SignUp() {
  const [name, setName] = createSignal('')
  const [email, setEmail] = createSignal('')
  const [password, setPassword] = createSignal('')
  const [error, setError] = createSignal('')

  async function handleSubmit(e: SubmitEvent) {
    e.preventDefault()
    setError('')
    try {
      const account = new Account(client)
      await account.create({
        userId: ID.unique(),
        email: email(),
        password: password(),
        name: name().trim() || undefined,
      })
      await account.createEmailPasswordSession({
        email: email(),
        password: password(),
      })
      window.location.href = '/'
    } catch (err) {
      setError(err instanceof Error ? err.message : 'Sign up failed')
    }
  }

  return (
    <form onSubmit={handleSubmit}>
      <h1>Sign up</h1>
      <Show when={error()}>
        <p>{error()}</p>
      </Show>
      <input
        type="text"
        placeholder="Name"
        value={name()}
        onInput={(e) => setName(e.currentTarget.value)}
      />
      <input
        type="email"
        placeholder="Email"
        value={email()}
        onInput={(e) => setEmail(e.currentTarget.value)}
        required
      />
      <input
        type="password"
        placeholder="Password"
        value={password()}
        onInput={(e) => setPassword(e.currentTarget.value)}
        required
      />
      <button type="submit">Sign up</button>
      <p>
        Already have an account? <a href="/sign-in">Sign in</a>
      </p>
    </form>
  )
}
